version: '3.3'
networks:
    postgres-database:
services:
    dhis2-postgres:
        image: postgres:9.6
        container_name: dhis2-postgres
        env_file:
            - db.env
        volumes:
            - ./database_schema.sql:/docker-entrypoint-initdb.d/database_schema.sql
            - ./db_data.sql:/docker-entrypoint-initdb.d/db_data.sql
        networks:
            - postgres-database

    dhis2:
        image: dhis2/dhis2-web:2.29-tomcat7-jre8-latest
        container_name: dhis2
        env_file:
            - db.env
        volumes:
            - ./dhis.conf:/usr/share/dhis2/dhis.conf
            - ./setenv.sh:/usr/local/tomcat/bin/setenv.sh
            - ./server.xml:/usr/local/tomcat/conf/server.xml
        ports:
            - "8084:8080"
        depends_on:
            - dhis2-postgres
        networks:
            - postgres-database